"""
Task:
    You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.
"""
from collections import defaultdict


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        result = 0

        for char in s:
            result ^= ord(char)

        for char in t:
            result ^= ord(char)

        return chr(result)


print(Solution().findTheDifference("abcd", "abcde"))  # e